cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    dbaldwin:
      email: dbaldwin@gmail.com
      failed_login_attempts: 1
      logged_in: false
      name: David Baldwin
      password: $2b$12$sBSEuNFavKdqRck4ZPaxLenSMrfySwZvehbQF1hFWDTtQwpbB8S6q
    gur12:
      email: gur@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: Gurminder
      password: $2b$12$CNtjn3zzu8rk5NkwuYf/eeWJwtxydpR736ITKBRNGokykDOX7yZbi
    gurminder:
      email: gurminder@gmail.com
      failed_login_attempts: 4
      logged_in: true
      name: Gurminder
      password: $2b$12$oQZGi6kvkcHyt0ogb5vVU.S6XHVVPyxWpguoOSfH7HAt0E8uwWvFG
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: John Smith
      password: $2b$12$pkBZODmBN/TsirSicCb1teFs6ERLn/mIdUY.UBTSvw5Y2xQEb492S
    noor1:
      email: gurnoor12@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Gurnoor
      password: $2b$12$W1dwiWz2Ad9c67sB6erq2uU2LuTgnz.vgXUn0H/S3ssRqzG0i5dhK
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Rebecca Briggs
      password: $2b$12$zZ9B03N/S0Dd28QRXI49bOaYrrp2mAwkumw.v5PYDvBBVoEktQUHy
    rishi117:
      email: rishavchopra1080@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Rishav Chopra
      password: $2b$12$czQVsQc6otbSUHxEyuQFsOzA.FvlwnEwY3r2s32LOeC/gOBh0e4AW
    shriya12:
      email: shriya123@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Shriya
      password: $2b$12$BP/bVo/71JjNXoFsOb5gZuOVs5.gCdaJYwxkBh9BP2fugAbmt/29y
pre-authorized:
  emails:
  - melsby@gmail.com
